name: ugd2_pbp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  intl: ^0.18.1
  sqflite: ^2.3.0
  form_builder_validators: ^9.1.0
  checkbox_formfield: ^0.2.0
  image_picker: ^1.0.4
  async: ^2.11.0
  path_provider: ^2.1.1
  flutter_slidable: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - images/
